#!/usr/bin/expect -f

set timeout -1
spawn ../client/sendmsg addleness.cert.pem addleness.key.pem somebody
match_max 100000
send -- "hello\r"
expect -exact "hello\r
"
send -- "\x04"
expect "Failed with code=400"
expect eof