#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: ./client_certificate <unique_identifier> <pass_in> <pass_out>"
    exit 1
fi

# Generate config file
./generate_config client_config.cnf intermediate $1 usr
mv client_config.cnf ./intermediate

# Only create private key if it does not exist
FILE=intermediate/private/$1.key.pem
if test -f "$FILE"; then
    echo "$FILE exists."
else
    # Create a private key
	openssl genrsa -aes256 \
        -out intermediate/private/$1.key.pem \
        -passout pass:$3 2048
fi

# Extract the public key
openssl rsa -in intermediate/private/$1.key.pem \
        -pubout > intermediate/public/$1.pub
chown $1 intermediate/private/$1.key.pem
chmod 400 intermediate/private/$1.key.pem
chmod 644 intermeidate/public/$1.pub

# Create a certificate
# 1. Certificate-Signing Request (CSR)
openssl req -config intermediate/client_config.cnf \
        -key intermediate/private/$1.key.pem \
        -new -sha256 -out intermediate/csr/$1.csr.pem \
        -passin pass:$2 -passout pass:$3

echo "Created CSR"

# 2. Use intermediate CA to sign CSR
openssl ca -config intermediate/client_config.cnf \
        -extensions usr_cert -days 375 -notext -md sha256 \
        -in intermediate/csr/$1.csr.pem \
        -out intermediate/certs/$1.cert.pem \
        -key $2 -passin pass:$2
chmod 444 intermediate/certs/$1.cert.pem

# Verify certificate
openssl verify -CAfile intermediate/certs/ca-chain.cert.pem \
        intermediate/certs/$1.cert.pem

