#!/bin/bash

if [ -d "$1" ]; then
	echo "Tree Exists"
	exit
fi

mkdir "$1"

cd "$1"
mkdir bin users tmp

input=("addleness" "analects" "annalistic" "anthropomorphologically" "blepharosphincterectomy" "corector" "durwaun" "dysphasia" "encampment" "endoscopic" "exilic" "forfend" "gorbellied" "gushiness" "muermo" "neckar" "outmate" "outroll" "overrich" "philosophicotheological" "pockwood" "polypose" "refluxed" "reinsure" "repine" "scerne" "starshine" "unauthoritativeness" "unminced" "unrosed" "untranquil" "urushinic" "vegetocarbonaceous" "wamara" "whaledom")

cd users

for i in ${input[@]}
do
	mkdir $i
	cd $i
	mkdir certs messages
	cd ..
done