#!/bin/bash

# Take command line arguments - there should be 1
if [ $# -ne 3 ]; then
    echo "Usage: ./client_certificate <unique_identifier> <pass_in> <pass_out>"
    exit 1
fi

cd root_ca

# Generate config file
.././generate_config encrypt_config.cnf . $1 encrypt 
mv encrypt_config.cnf ./intermediate

# Create a key
openssl genrsa -aes256 \
        -out intermediate/private/$1.key.pem \
        -passout pass:$3 2048
chmod 400 intermediate/private/$1.key.pem

# Create a certificate
# 1. Certificate-Signing Request (CSR)
openssl req -config intermediate/encrypt_config.cnf \
        -key intermediate/private/$1.key.pem \
        -new -sha256 -out intermediate/csr/$1.csr.pem \
        -passin pass:$2 -passout pass:$3

echo "created csr"

# 2. Use intermediate CA to sign CSR
openssl ca -config intermediate/encrypt_config.cnf \
        -extensions usr_cert -days 375 -notext -md sha256 \
        -in intermediate/csr/$1.csr.pem \
        -out intermediate/certs/$1.cert.pem \
        -key $2 -passin pass:$2
chmod 444 intermediate/certs/$1.cert.pem

# Verify certificate
openssl verify -CAfile intermediate/certs/ca-chain.cert.pem \
        intermediate/certs/$1.cert.pem

